language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl --version
  - pear config-set php_ini ~/.phpenv/versions/`php -r 'echo phpversion();'`/etc/php.ini
  - pecl install uri_template-beta
  - composer install
  - ~/.nvm/nvm.sh install v0.6.14
  - ~/.nvm/nvm.sh run v0.6.14

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
