name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-lowest-version:
    name: Build lowest version
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: '7.2'
          coverage: xdebug
          ini-values: xdebug.overload_var_dump=1
          extensions: mbstring, intl
          tools: prestissimo

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: composer update --no-interaction --prefer-stable --prefer-lowest --prefer-dist

      - name: Run tests
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-values: xdebug.overload_var_dump=1
          extensions: mbstring, intl
          tools: prestissimo

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run tests
        run: make test
